# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 966f6a8e455c7df69105e9ae2495447e23f3c00faf3bfc315bad2901af051fa72f927612ce58cdacaa776a4a75cff1303566edb7fd8652519456946436071d78

test:
  secret_key_base: 3eee6b094c4b1848b013b3678a6dee30f35f9a074e452b24df50650589360ea39b0b2a96e78a8c523eed0eb591f686974a2d654f67dc2e4c0ca46afc7d49b7cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
